export default [
  'A-1',
  'amazing',
  'at this rate, you\'ll conquer the world',
  'awesome job 🎉',
  'brilliant',
  'champion 🤩',
  'congrats',
  'cool',
  'cool cool',
  'cracking effort 👏',
  'crushin’ it',
  'dynamite',
  'excellent',
  'extraordinary',
  'fabulous',
  'fantastic',
  'go go go',
  'good job',
  'great work',
  'great job! 💕',
  'hundo P',
  'impeccable',
  'impressive',
  'incredible',
  'jumptastic 🤩',
  'kablaam',
  'ka-ching',
  'keep going',
  'keep it up',
  'keep on going ❤️',
  'keep \'em coming',
  'keep up the great work',
  'killin\' it',
  'kowabunga dude',
  'lit',
  'magnificent',
  'marvelous',
  'mind blowing',
  'nice',
  'nice work',
  'nice work 🤗',
  'niiiice',
  'omg',
  'outstanding',
  'outstanding 🤩🤩🤩',
  'remarkable',
  'right-o',
  'sensational',
  'so impressed',
  'so lit',
  'sound 👌',
  'superb',
  'sweet',
  'that\'s lit',
  'that’s amazing',
  'top notch',
  'tremendous',
  'very good',
  'well done',
  'wonderful',
  'woo hoo',
  'woot woot',
  'wow',
  'wow, nice',
  'wow, you can really dance',
  'wowza',
  '👑 yass queen',
  'yaaassss',
  'yabadabadoo',
  'yay',
  'yippeeeee',
  'yowza',
  'you are rocking this',
  'you did it',
  'you rock',
  'you\'re amazing',
  '🤯 you blow my mind',
  'you\'re doing wonderfully',
  'you\'re on a roll',
  '🎉🎉🎉super sonic',
  '🎆',
  '🎇',
  '🎉',
  '🎊',
  '🎖',
  '🏅',
  '🏆',
  '👌',
  '👍👍',
  '👏👏👏',
  '👯‍♀️',
  '👯‍♀️',
  '👯‍♂️',
  '👻',
  '💃',
  '💓',
  '💪',
  '💯',
  '🔥🔥🔥',
  '🕺',
  '😍',
  '🤯',
  '🤩🤩🤩',
  '😎😎😎',
  '🙌',
  '🥇',
  '🦄🦄🦄',
  '✅✅✅✅✅',
];
