// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ActivityTimelineItem: typeof import('./../components/ActivityTimelineItem.vue')['default']
    AddCompliment: typeof import('./../components/AddCompliment.vue')['default']
    AddNewTip: typeof import('./../components/AddNewTip.vue')['default']
    ChallengeInfo: typeof import('./../components/ChallengeInfo.vue')['default']
    ChallengeProgress: typeof import('./../components/ChallengeProgress.vue')['default']
    EditChallenge: typeof import('./../components/EditChallenge.vue')['default']
    EditGroup: typeof import('./../components/EditGroup.vue')['default']
    FilterBy: typeof import('./../components/FilterBy.vue')['default']
    HorizontalBarChart: typeof import('./../components/HorizontalBarChart.vue')['default']
    Loader: typeof import('./../components/Loader.vue')['default']
    Picker: typeof import('./../components/Picker.vue')['default']
    SortBy: typeof import('./../components/SortBy.vue')['default']
  }
}

export { }
